name: Auto Deploy to WSL

# Only proceed if CI (Build & Test) is successful, or can be done when pushing to main
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    # HERE'S THE KEY: Don't use ubuntu-latest, use the agent in our WSL!
    runs-on: self-hosted

    steps:
      - name: Pull Latest Code & Restart Docker
        # Replace /home/valenrio66/be-project with the actual path of your project folder in WSL
        run: |
          cd /home/valenrio66/be-project
          git pull origin main
          docker compose up -d --build